# site settings
title: Varad Deshmukh
subtitle: by HTML5 UP
email: varad [dot] deshmukh [at] colorado.edu 
description: 
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 17611 W 16TH AVE APT 208
city: Golden
state: CO
zip_code: 80401
country: United States of America
phone: (707) 567-8795

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 12

# social settings
500px_url:
facebook_url:
github_url: https://github.com/vrd1243
gitlab_url: 
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com/vrd1618
linkedin_url: https://www.linkedin.com/in/varad-deshmukh-b5367823/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/vrd1243

# build settings
markdown: kramdown

sass:
  style: compressed
